services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        python manage.py makemigrations user_service &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        uvicorn core.asgi:application --host 0.0.0.0 --port 8000
      "
    ports:
      - "8003:8000"
    environment:
      - ALLOWED_HOSTS=*
    container_name: user-service
    networks:
      - raijmobi-network

networks:
  raijmobi-network:
    external: true