services:
  zookeeper-user:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: zookeeper-user
    networks:
      - raijmobi-network

  kafka-user:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper-user
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-user:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-user:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    container_name: kafka-user
    networks:
      - raijmobi-network

  # 1. NOVO SERVIÇO: O Broker (Redis)
  redis-user:
    image: redis:alpine
    container_name: redis-user
    ports:
      - "6379:6379"
    networks:
      - raijmobi-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        echo 'Aguardando PostgreSQL...' &&
        sleep 10 &&
        python manage.py makemigrations user_service --noinput &&
        python manage.py migrate --noinput &&
        python manage.py createsuperuser --noinput || true &&
        python manage.py collectstatic --noinput &&
        uvicorn core.asgi:application --host 0.0.0.0 --port 8000
      "

    ports:
      - "8003:8000"
    environment:
      - DB_NAME=raijmobi_user_db
      - DB_USER=raijmobi_user
      - DB_PASSWORD=raijmobi_pass
      - DB_HOST=postgres-user
      - DB_PORT=5432
      - GOOGLE_CLIENT_ID=fake-google-client-id
      - KAFKA_BOOTSTRAP_SERVERS=kafka-user:9092
      - ALLOWED_HOSTS=*
      - DJANGO_SUPERUSER_EMAIL=pablo.murilo10@hotmail.com
      - DJANGO_SUPERUSER_NOME=Admin
      - DJANGO_SUPERUSER_PASSWORD=am@21star
      # Novas variáveis para o Celery e Resend
      - CELERY_BROKER_URL=redis://redis-user:6379/0
      - RESEND_API_KEY=sua_chave_do_resend_aqui
    depends_on:
      - kafka-user
      - redis-user # API agora espera o Redis subir
    container_name: user-service
    networks:
      - raijmobi-network

  


  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: raijmobi_user_db
      POSTGRES_USER: raijmobi_user
      POSTGRES_PASSWORD: raijmobi_pass
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raijmobi_user -d raijmobi_user_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - raijmobi-network

  # ========== MANUTENÇÃO AUTOMÁTICA (VACUUM / REINDEX) ==========
  db-maintenance:
    build:
      context: ./maintenance
      dockerfile: Dockerfile
    container_name: postgres-user-maintenance
    depends_on:
      postgres-user:
        condition: service_healthy
    environment:
      - DB_HOST=postgres-user
      - DB_PORT=5432
      - DB_NAME=raijmobi_user_db
      - DB_USER=raijmobi_user
      - DB_PASSWORD=raijmobi_pass
      - MAINTENANCE_INTERVAL_SECONDS=86400   # 24h
      - TZ=America/Sao_Paulo
      # - LOG_DIR=/app/logs     # descomente se mapear logs no futuro
      # - LOG_RETENTION_DAYS=30
    networks:
      - raijmobi-network

  db-backup:
    build:
      context: ../RaijMobi-Services-postgres-backups/User-service        # <-- agora aponta para a nova pasta
      dockerfile: Dockerfile
    container_name: postgres-user-db-backup
    environment:
      - DB_HOST=postgres-user
      - DB_PORT=5432
      - DB_NAME=raijmobi_user_db
      - DB_USER=raijmobi_user
      - DB_PASSWORD=raijmobi_pass
      - BACKUP_DIR=/backups
      - BACKUP_INTERVAL_SECONDS=86400   # 24 horas
      - RETENTION_DAYS=7                # opcional, mantém últimos 7 dias
      - TZ=America/Sao_Paulo
    volumes:
      - backup_user_data:/backups
    networks:
      - raijmobi-network
    depends_on:
      postgres-user:
        condition: service_healthy


  celery-worker-user:
    build:
      context: .
      dockerfile: Dockerfile
    # Note que usamos 'core' baseando-se no 'core.asgi' do seu user-service
    command: celery -A core worker --loglevel=info
    environment:
      # O worker precisa das mesmas variáveis de ambiente que a API
      # pois ele carrega toda a aplicação Django em memória
      - KAFKA_BOOTSTRAP_SERVERS=kafka-user:9092
      - ALLOWED_HOSTS=*
      - CELERY_BROKER_URL=redis://redis-user:6379/0
      - RESEND_API_KEY=re_6iH6dPfU_BcvypGyFpgaQkqvH6AzhuAd9
      - DB_HOST=postgres-user
      - DB_PORT=5432
      - DB_NAME=raijmobi_user_db
      - DB_USER=raijmobi_user
      - DB_PASSWORD=raijmobi_pass
    depends_on:
      - kafka-user
      - redis-user
      - user-service 
    networks:
      - raijmobi-network

volumes:
  postgres_user_data:
  backup_user_data: 
  
networks:
  raijmobi-network:
    external: true