services:

  zookeeper-user:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: zookeeper-user
    networks:
      - raijmobi-network

  kafka-user:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper-user
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-user:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-user:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    container_name: kafka-user
    networks:
      - raijmobi-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        python manage.py makemigrations user_service --noinput &&
        python manage.py migrate &&
        python manage.py createsuperuser --noinput || true &&
        python manage.py collectstatic --noinput &&
        uvicorn core.asgi:application --host 0.0.0.0 --port 8000
      "
    ports:
      - "8003:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-user:9092
      - ALLOWED_HOSTS=*
      - DJANGO_SUPERUSER_EMAIL=admin@raijmobi.com
      - DJANGO_SUPERUSER_NOME=Admin
      - DJANGO_SUPERUSER_PASSWORD=suasenhaaqui
    depends_on:
      - kafka-user
    container_name: user-service
    networks:
      - raijmobi-network


networks:
  raijmobi-network:
    external: true