# Generated by Django 5.2.14 on 2026-05-07 17:36

import django.db.models.deletion
import django.utils.timezone
import user_service.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_motorista',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_campus',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[user_service.validators.validar_cpf])),
                ('telefone', models.CharField(max_length=15)),
                ('tipo_usuario', models.CharField(choices=[('Motorista', 'Motorista'), ('Passageiro', 'Passageiro')], max_length=50)),
                ('tipo_campus', models.CharField(choices=[('Campus Natal-Central', 'Campus Natal-Central'), ('Campus Mossoró', 'Campus Mossoró')], max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('is_motorista', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
