# Generated by Django 5.2.14 on 2026-05-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0004_auto_20170620_1354_squashed_0019_alter_crudevent_changed_fields_and_more'),
        ('user_service', '0002_remove_usuario_cpf_remove_usuario_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria de Perfil',
                'verbose_name_plural': 'Auditorias de Perfis',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.CreateModel(
            name='UsuarioAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria de Usuário',
                'verbose_name_plural': 'Auditorias de Usuários',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo_campus',
        ),
    ]
